version: '3.5'

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "32481:2181"
    volumes:
      - "../01-config/01-zookeeper:/etc/kafka/config"
  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    container_name: kafka
    ports:
      - "39492:9092"
    volumes:
      # - "${KAFKA_DATA}/41-04-kafka-cert:/etc/kafka/secrets:ro"
      - "../01-config/11-kafka:/etc/kafka/config"
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
