KafkaServer {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    // 用於訪問其他節點
    username="geting"
    password="geting"
    // 表示創建一個新用為 戶名alice 及密碼alice
    user_geting="geting"
    user_alice="alice"; 
};

// 用於連接到 zookeeper
KafkaClient {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="geting"
    password="geting";
};



